{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyNuqHSbJNc8xQFEabTga7Y0",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/playingwithgithub24/HackBio-Single-Cell-RNA-Sequencing/blob/main/Simple_Code.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "ViFHtHCe4AM0",
        "outputId": "cee8620c-9b08-4d41-8854-d0e137e5ef4b"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "============================================================\n",
            "Name: Antara Ghanta\n",
            "Slack Username: @Antara\n",
            "Country: India\n",
            "Hobby: Reading\n",
            "Affiliation: Nottingham Trent University, UK\n",
            "Favourite Gene: HMOX1 - Heme Oxygenase 1\n",
            "DNA Sequence of Favoured Gene:\n",
            "NC_000022.11:35381096-35394207 HMOX1 [organism=Homo sapiens] [GeneID=3162] [chromosome=22]\n",
            "    AACGCCTGCCTCCTCTCGAGCGTCCTCAGCGCAGCCGCCGCCCGC\n",
            "============================================================ \n",
            "\n",
            "============================================================\n",
            "Name: Lucia Uchegbu\n",
            "Slack Username: @Lucia\n",
            "Country: Nigeria\n",
            "Hobby: Social Media Management\n",
            "Affiliation: Federal University Oye-Ekiti Nigeria\n",
            "Favourite Gene: TP53 Tumor Protein\n",
            "DNA Sequence of Favoured Gene:\n",
            "TP53 [organism=Homo sapiens] [GeneID=7157] [RefSeq=NM_000546.6] [region=cds]\n",
            "    ATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCC\n",
            "============================================================ \n",
            "\n",
            "============================================================\n",
            "Name: Archana Nadig\n",
            "Slack Username: @Archana\n",
            "Country: India\n",
            "Hobby: Playing Chess\n",
            "Affiliation: University of York, UK\n",
            "Favourite Gene: Tinman\n",
            "DNA Sequence of Favoured Gene:\n",
            "NT_033777.3:21378977-21381970 Drosophila melanogaster chromosome 3R\n",
            "    TCAGTACCAAAATCGAGCTGACAAATTGCAGAC\n",
            "============================================================ \n",
            "\n",
            "============================================================\n",
            "Name: Samuella Ebeny\n",
            "Slack Username: @Sam NY\n",
            "Country: France\n",
            "Hobby: Reading\n",
            "Affiliation: Sorbonne University\n",
            "Favourite Gene: SLC9A2\n",
            "DNA Sequence of Favoured Gene:\n",
            "NC_000002.12:102619553-102711355 Homo sapiens chromosome 2, GRCh38.p14 Primary Assembly\n",
            "    GGAGAGCAGCGCACCGGCATGGGCAGGCGGCCGGCGGC\n",
            "============================================================ \n",
            "\n",
            "============================================================\n",
            "Name: Chimbusonma Amaechina\n",
            "Slack Username: @Sonma\n",
            "Country: Nigeria\n",
            "Hobby: Reading\n",
            "Affiliation: Grambling State University, United States\n",
            "Favourite Gene: BRCA1\n",
            "DNA Sequence of Favoured Gene:\n",
            "NC_000017.11:43044295-43170245 Homo sapiens chromosome 17, GRCh38.p14 Primary Assembly\n",
            "    ATGGATTTATCTGCTCTTCGGAAAAGCAAGAGGCTGCTGAGGATC\n",
            "============================================================ \n",
            "\n",
            "============================================================\n",
            "Name: Khanh Gia Duong\n",
            "Slack Username: @Khanh\n",
            "Country: Vietnam\n",
            "Hobby: Watching Movies\n",
            "Affiliation: Asian University for Women\n",
            "Favourite Gene: BRCA1\n",
            "DNA Sequence of Favoured Gene:\n",
            "NC_000017.11:43044295-43170245 Homo sapiens chromosome 17, GRCh38.p14 Primary Assembly\n",
            "    ATGGATTTATCTGCTCTTCGGAAAAGCAAGAGGCTGCTGA\n",
            "============================================================ \n",
            "\n",
            "============================================================\n",
            "Name: Herimampionona Antsaniony\n",
            "Slack Username: @Antsaniony\n",
            "Country: Madagascar\n",
            "Hobby: Hiking\n",
            "Affiliation: University of Antananarivo\n",
            "Favourite Gene: CD79a\n",
            "DNA Sequence of Favoured Gene:\n",
            "NM_001783.4 Homo sapiens CD79a molecule (CD79A), transcript variant 1, mRNA\n",
            "    CAAACTAACCAACCCACTGGGAGAAGATGCCTGGGGGTCCAGG\n",
            "============================================================ \n",
            "\n",
            "============================================================\n",
            "Name: Saumi Shah\n",
            "Slack Username: @Antsaniony\n",
            "Country: India\n",
            "Hobby: Listening to song\n",
            "Affiliation: SJSU\n",
            "Favourite Gene: TNF\n",
            "DNA Sequence of Favoured Gene:\n",
            ">NC_000006.12:31575565-31578336 Homo sapiens chromosome 6, GRCh38.p14 Primary Assembly\n",
            "AGCAGACGCTCCCTCAGCAAGGACAGCAGAGGACCAGCTAAGAGGGAGAGAAGCAACTACAGA\n",
            "============================================================ \n",
            "\n",
            "============================================================\n",
            "Name: Sarah Adeyemi\n",
            "Slack Username: @Sarah4God\n",
            "Country: USA\n",
            "Hobby: Reading\n",
            "Affiliation: Morgan State University\n",
            "Favourite Gene: TNF\n",
            "DNA Sequence of Favoured Gene:\n",
            ">NC_000006.12:31575565-31578336 Homo sapiens chromosome 6, GRCh38.p14 Primary Assembly\n",
            "AGCAGACGCTCCCTCAGCAAGGACAGCAGAGGACCAGCTAAGAGGGAGAGAAGCAACTACAGA\n",
            "============================================================ \n",
            "\n"
          ]
        }
      ],
      "source": [
        "#HackBioInternship: Team Histidine Stage 0 Task\n",
        "\n",
        "#Task:\n",
        "# A simple python script for printing the names, slack username, country,\n",
        "# 1 hobby, affiliations of people on your team and\n",
        "# and the DNA sequence of the genes they love most.\n",
        "#Author:Antara Ghanta\n",
        "#GitHub:https://github.com/playingwithgithub24\n",
        "#Linkedin: www.linkedin.com/in/antara-ghanta\n",
        "\n",
        "#Step1 - Stored team Histidine member's information in Tuples\n",
        "\n",
        "Antara = (\n",
        "    \"Antara Ghanta\",  # Name\n",
        "    \"@Antara\",        # Slack Username\n",
        "    \"India\",          # Country\n",
        "    \"Reading\",        # Hobby\n",
        "    \"Nottingham Trent University, UK\",  # Affiliation\n",
        "    \"HMOX1 - Heme Oxygenase 1\",  # Favourite Gene\n",
        "    \"\"\"NC_000022.11:35381096-35394207 HMOX1 [organism=Homo sapiens] [GeneID=3162] [chromosome=22]\n",
        "    AACGCCTGCCTCCTCTCGAGCGTCCTCAGCGCAGCCGCCGCCCGC\"\"\"  # DNA Sequence\n",
        ")\n",
        "\n",
        "Lucia = (\n",
        "    \"Lucia Uchegbu\",  # Name\n",
        "    \"@Lucia\",         # Slack Username\n",
        "    \"Nigeria\",        # Country\n",
        "    \"Social Media Management\",  # Hobby\n",
        "    \"Federal University Oye-Ekiti Nigeria\",  # Affiliation\n",
        "    \"TP53 Tumor Protein\",  # Favourite Gene\n",
        "    \"\"\"TP53 [organism=Homo sapiens] [GeneID=7157] [RefSeq=NM_000546.6] [region=cds]\n",
        "    ATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCC\"\"\"  # DNA Sequence\n",
        ")\n",
        "\n",
        "Archana = (\n",
        "    \"Archana Nadig\",  # Name\n",
        "    \"@Archana\",       # Slack Username\n",
        "    \"India\",          # Country\n",
        "    \"Playing Chess\",  # Hobby\n",
        "    \"University of York, UK\",  # Affiliation\n",
        "    \"Tinman\",         # Favourite Gene\n",
        "    \"\"\"NT_033777.3:21378977-21381970 Drosophila melanogaster chromosome 3R\n",
        "    TCAGTACCAAAATCGAGCTGACAAATTGCAGAC\"\"\"  # DNA Sequence\n",
        ")\n",
        "\n",
        "Sam = (\n",
        "    \"Samuella Ebeny\",  # Name\n",
        "    \"@Sam NY\",         # Slack Username\n",
        "    \"France\",          # Country\n",
        "    \"Reading\",         # Hobby\n",
        "    \"Sorbonne University\",  # Affiliation\n",
        "    \"SLC9A2\",          # Favourite Gene\n",
        "    \"\"\"NC_000002.12:102619553-102711355 Homo sapiens chromosome 2, GRCh38.p14 Primary Assembly\n",
        "    GGAGAGCAGCGCACCGGCATGGGCAGGCGGCCGGCGGC\"\"\"  # DNA Sequence\n",
        ")\n",
        "\n",
        "Chimbusonma = (\n",
        "    \"Chimbusonma Amaechina\",  # Name\n",
        "    \"@Sonma\",                 # Slack Username\n",
        "    \"Nigeria\",                # Country\n",
        "    \"Reading\",                # Hobby\n",
        "    \"Grambling State University, United States\",  # Affiliation\n",
        "    \"BRCA1\",                  # Favourite Gene\n",
        "    \"\"\"NC_000017.11:43044295-43170245 Homo sapiens chromosome 17, GRCh38.p14 Primary Assembly\n",
        "    ATGGATTTATCTGCTCTTCGGAAAAGCAAGAGGCTGCTGAGGATC\"\"\"  # DNA Sequence\n",
        ")\n",
        "\n",
        "Khanh = (\n",
        "    \"Khanh Gia Duong\",  # Name\n",
        "    \"@Khanh\",           # Slack Username\n",
        "    \"Vietnam\",          # Country\n",
        "    \"Watching Movies\",  # Hobby\n",
        "    \"Asian University for Women\",  # Affiliation\n",
        "    \"BRCA1\",            # Favourite Gene\n",
        "    \"\"\"NC_000017.11:43044295-43170245 Homo sapiens chromosome 17, GRCh38.p14 Primary Assembly\n",
        "    ATGGATTTATCTGCTCTTCGGAAAAGCAAGAGGCTGCTGA\"\"\"  # DNA Sequence\n",
        ")\n",
        "\n",
        "Antsaniony = (\n",
        "    \"Herimampionona Antsaniony\",  # Name\n",
        "    \"@Antsaniony\",                # Slack Username\n",
        "    \"Madagascar\",                 # Country\n",
        "    \"Hiking\",                     # Hobby\n",
        "    \"University of Antananarivo\", # Affiliation\n",
        "    \"CD79a\",                      # Favourite Gene\n",
        "    \"\"\"NM_001783.4 Homo sapiens CD79a molecule (CD79A), transcript variant 1, mRNA\n",
        "    CAAACTAACCAACCCACTGGGAGAAGATGCCTGGGGGTCCAGG\"\"\"  # DNA Sequence\n",
        ")\n",
        "\n",
        "Saumi = (\n",
        "    \"Saumi Shah\",                # Name\n",
        "    \"@Antsaniony\",               # Slack Username\n",
        "    \"India\",                     # Country\n",
        "    \"Listening to song\",         # Hobby\n",
        "    \"SJSU\",                      # Affiliation\n",
        "    \"TNF\",                       # Favourite Gene\n",
        "    \"\"\">NC_000006.12:31575565-31578336 Homo sapiens chromosome 6, GRCh38.p14 Primary Assembly\n",
        "AGCAGACGCTCCCTCAGCAAGGACAGCAGAGGACCAGCTAAGAGGGAGAGAAGCAACTACAGA\"\"\"  # DNA Sequence\n",
        ")\n",
        "\n",
        "Sarah = (\n",
        "    \"Sarah Adeyemi\",             # Name\n",
        "    \"@Sarah4God\",                # Slack Username\n",
        "    \"USA\",                       # Country\n",
        "    \"Reading\",                  # Hobby\n",
        "    \"Morgan State University\",   # Affiliation\n",
        "    \"TNF\",                       # Favourite Gene\n",
        "    \"\"\">NC_000006.12:31575565-31578336 Homo sapiens chromosome 6, GRCh38.p14 Primary Assembly\n",
        "AGCAGACGCTCCCTCAGCAAGGACAGCAGAGGACCAGCTAAGAGGGAGAGAAGCAACTACAGA\"\"\"  # DNA Sequence\n",
        ")\n",
        "\n",
        "#Step 2- Print the Data\n",
        "\n",
        "team = [Antara, Lucia, Archana, Sam, Chimbusonma, Khanh, Antsaniony, Saumi, Sarah]\n",
        "for member in team:\n",
        "    print(\"=\" * 60)\n",
        "    print(f\"Name: {member[0]}\")\n",
        "    print(f\"Slack Username: {member[1]}\")\n",
        "    print(f\"Country: {member[2]}\")\n",
        "    print(f\"Hobby: {member[3]}\")\n",
        "    print(f\"Affiliation: {member[4]}\")\n",
        "    print(f\"Favourite Gene: {member[5]}\")\n",
        "    print(\"DNA Sequence of Favoured Gene:\")\n",
        "    print(member[6])\n",
        "    print(\"=\" * 60, \"\\n\")\n"
      ]
    }
  ]
}