# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DBzSNOFOz01KLqFgr8Ro4TujEKfPr-tF
"""

# HackBio Internship – Team Histidine Stage 0 Task
# Task: Print names, Slack usernames, countries, hobbies, affiliations, and DNA sequences of favorite genes
# Author: Antara Ghanta
# GitHub: https://github.com/playingwithgithub24/HackBio-Single-Cell-RNA-Sequencing
# LinkedIn: www.linkedin.com/in/antara-ghanta

# Step 1 – Store team data in a list of dictionaries
team_histidine = [
    {
        "Name": "Antara Ghanta",
        "Slack": "@Antara",
        "Country": "India",
        "Hobby": "Reading",
        "Affiliation": "Nottingham Trent University, UK",
        "Gene": "HMOX1 - Heme Oxygenase 1",
        "DNA": """NC_000022.11:35381096-35394207 HMOX1 [organism=Homo sapiens] [GeneID=3162] [chromosome=22]
AACGCCTGCCTCCTCTCGAGCGTCCTCAGCGCAGCCGCCGCCCGCGGAGCCAGCACGAACGAGCCCAGCA"""
    },
    {
        "Name": "Lucia Uchegbu",
        "Slack": "@Lucia",
        "Country": "Nigeria",
        "Hobby": "Social Media Management",
        "Affiliation": "Federal University Oye-Ekiti Nigeria",
        "Gene": "TP53 Tumor Protein",
        "DNA": """TP53 [organism=Homo sapiens] [GeneID=7157] [RefSeq=NM_000546.6] [region=cds]
ATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCC"""
    },
    {
        "Name": "Archana Nadig",
        "Slack": "@Archana",
        "Country": "India",
        "Hobby": "Playing Chess",
        "Affiliation": "University of York, UK",
        "Gene": "Tinman",
        "DNA": """NT_033777.3:21378977-21381970 Drosophila melanogaster chromosome 3R
TCAGTACCAAAATCGAGCTGACAAATTGCAGAC"""
    },
    {
        "Name": "Samuella Ebeny",
        "Slack": "@Sam NY",
        "Country": "France",
        "Hobby": "Reading",
        "Affiliation": "Sorbonne University",
        "Gene": "SLC9A2",
        "DNA": """NC_000002.12:102619553-102711355 Homo sapiens chromosome 2, GRCh38.p14 Primary Assembly
GGAGAGCAGCGCACCGGCATGGGCAGGCGGCCGGCGGC"""
    },
    {
        "Name": "Chimbusonma Amaechina",
        "Slack": "@Sonma",
        "Country": "Nigeria",
        "Hobby": "Reading",
        "Affiliation": "Grambling State University, United States",
        "Gene": "BRCA1",
        "DNA": """NC_000017.11:43044295-43170245 Homo sapiens chromosome 17, GRCh38.p14 Primary Assembly
ATGGATTTATCTGCTCTTCGGAAAAGCAAGAGGCTGCTGAGGATC"""
    },
    {
        "Name": "Khanh Gia Duong",
        "Slack": "@Khanh",
        "Country": "Vietnam",
        "Hobby": "Watching Movies",
        "Affiliation": "Asian University for Women",
        "Gene": "BRCA1",
        "DNA": """NC_000017.11:43044295-43170245 Homo sapiens chromosome 17, GRCh38.p14 Primary Assembly
ATGGATTTATCTGCTCTTCGGAAAAGCAAGAGGCTGCTGA"""
    },
    {
        "Name": "Herimampionona Antsaniony",
        "Slack": "@Antsaniony",
        "Country": "Madagascar",
        "Hobby": "Hiking",
        "Affiliation": "University of Antananarivo",
        "Gene": "CD79a",
        "DNA": """NM_001783.4 Homo sapiens CD79a molecule (CD79A), transcript variant 1, mRNA
CAAACTAACCAACCCACTGGGAGAAGATGCCTGGGGGTCCAGG"""
    },
    {
        "Name": "Saumi Shah",
        "Slack": "@Saumi",
        "Country": "India",
        "Hobby": "Listening to songs",
        "Affiliation": "SJSU",
        "Gene": "TNF",
        "DNA": """>NC_000006.12:31575565-31578336 Homo sapiens chromosome 6, GRCh38.p14 Primary Assembly
AGCAGACGCTCCCTCAGCAAGGACAGCAGAGGACCAGCTAAGAGGGAGAGAAGCAACTACAGA"""
    },
    {
        "Name": "Sarah Adeyemi",
        "Slack": "@Sarah4God",
        "Country": "USA",
        "Hobby": "Reading",
        "Affiliation": "Morgan State University",
        "Gene": "TNF",
        "DNA": """>NC_000006.12:31575565-31578336 Homo sapiens chromosome 6, GRCh38.p14 Primary Assembly
AGCAGACGCTCCCTCAGCAAGGACAGCAGAGGACCAGCTAAGAGGGAGAGAAGCAACTACAGA"""
    }
]

# Step 2 – Define a function to print member details
def print_member_info(member):
    """
    Prints formatted information for a single team member.
    Includes basic error handling for missing fields.
    """
    try:
        print("=" * 60)
        print(f"Name: {member['Name']}")
        print(f"Slack Username: {member['Slack']}")
        print(f"Country: {member['Country']}")
        print(f"Hobby: {member['Hobby']}")
        print(f"Affiliation: {member['Affiliation']}")
        print(f"Favourite Gene: {member['Gene']}")
        print("DNA Sequence of Favoured Gene:")
        print(member['DNA'])
        print("=" * 60, "\n")
    except KeyError as e:
        print(f"Missing field: {e} in member data.\n")

# Step 3 – Loop through team and print info
for member in team_histidine:
    print_member_info(member)

# Scientific Note:
# This script prints metadata and DNA sequences of genes favored by HackBio interns.
# While not analytical, it sets the stage for future bioinformatics tasks such as
# sequence alignment, motif discovery, or expression profiling in single-cell RNA-seq.